spring.application.name=CentroBus
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.file.name=logs/system.log

database.password=csc380!S26!T4

# Use secure placeholders instead of real keys!
centro.key=${CENTRO_KEY}
openweather.key=${OPENWEATHER_KEY}

admin.username=admin
admin.passwordHash=c797c66fb71384dcd05f4